name: loglytics
description: An efficient, user-friendly way to implement logs, analytics and crash reports into your projects.
version: 0.14.1
homepage: https://github.com/codaveto/loglytics

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
